apiVersion: v1
kind: Pod
metadata:
  name: my-service-account
  namespace: class24-rbac
spec:
  serviceAccountName: my-service-account
  containers:
  - name: nginx
    image: nginx:latest
    command: ["sleep", "3600"]