apiVersion: v1
kind: Namespace
metadata:
  name: staging
spec: {}
status: {}
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: staging
spec:
  hard:
    pods: "2"
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 4Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: pod-limitrange
  namespace: staging
spec:
  limits:
  - default:
      cpu: "250m"
      memory: 512Mi
    defaultRequest:
      cpu: "100m"
      memory: 256Mi
    type: Container
